server:
  port: 8000

spring:
  application:
    name: api-gateway

zuul:
  ignoredServices: '*'
  routes:
    material-service:
      path: /material-service/**
      service-id: material-service
      stripPrefix: true

endpoints:
  routes:
    sensitive: false

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      default-zone: http://service-registry:8761/eureka/